version: '3'


services: 
  backend: 
    image: 'tom/backend:latest'
    build:
      dockerfile: Dockerfile.backend.dockerfile
      context: . 
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/shared

  frontend: 
    image: 'tom/frontend:latest'
    build:
      dockerfile: Dockerfile.frontend.dockerfile
      context: . 
    ports:
      - "8080:80"
