version: '3'


services: backend: image:
  docker.io/your_username/backend:latest ports:
  -	"3000:3000" volumes:
  -	./shared:/shared


frontend: image:
  docker.io/your_username/frontend:latest ports:
  - "8080:80"
