# This is the configuration file for the API service
# It follows the struct in cmd/webapi/load-configuration.go

log:
  debug: true
  filename: "-"

web:
  apihost: http://localhost:3000
  readtimeout: 5s
  writetimeout: 5s
  shutdowntimeout: 5s
